### ISSUE TITLE
server terminal client, setting iso is broken

### ISSUE THREAD

**Issue by neilthomson** [waveform80/compoundpi#38]
When I tried 

cpi> iso 800

I got

```
Traceback (most recent call last):
  File "/usr/bin/cpi", line 9, in <module>
    load_entry_point('compoundpi==0.3', 'console_scripts', 'cpi')()
  File "/usr/lib/python2.7/dist-packages/compoundpi/terminal.py", line 138, in
__call__
    return self.main(args) or 0
  File "/usr/lib/python2.7/dist-packages/compoundpi/cli.py", line 172, in main
    proc.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/dist-packages/compoundpi/cmdline.py", line 236, in
onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/dist-packages/compoundpi/cli.py", line 954, in
do_iso
    value, self.parse_arg(arg[1] if len(arg) > 1 else None))
NameError: global name 'value' is not defined
```

**Comment by waveform80** [comment]
Ah, looks like I fixed that back in dd4c4ada972baee3e1f4b304137b732fbe60ce28. It's working fine in the current development head but I'd warn against using that for production purposes at the moment; it's in a certain amount of flux while I try and polish off 0.4 (nearly there - just need to finish off server sorting in the GUI client, and flesh out the tests but time is proving difficult to come by at the moment!)
