### ISSUE TITLE
Server cpid

### ISSUE THREAD

**Issue by jricardogil** [waveform80/compoundpi#51]
When I run cpid on the lxterminal I get the next log:
I'm running the compoundpi server on a raspberry pi zero with raspbian
Compundpi --version 0.4
Status Active: running
What can I do i cant find the servers on the client running on raspbian jessie on a pi 3 
Traceback (most recent call last):
  File "/usr/sbin/cpid", line 9, in <module>
    load_entry_point('compoundpi==0.4', 'console_scripts', 'cpid')()
  File "/usr/lib/python2.7/dist-packages/compoundpi/terminal.py", line 138, in __call__
    return self.main(args) or 0
  File "/usr/lib/python2.7/dist-packages/compoundpi/server.py", line 213, in main
    signal.SIGINT:  self.interrupt,
  File "/usr/lib/pymodules/python2.7/daemon/daemon.py", line 352, in __enter__
    self.open()
  File "/usr/lib/pymodules/python2.7/daemon/daemon.py", line 344, in open
    self.pidfile.__enter__()
  File "/usr/lib/pymodules/python2.7/lockfile.py", line 223, in __enter__
    self.acquire()
  File "/usr/lib/pymodules/python2.7/daemon/pidlockfile.py", line 109, in acquire
    super(TimeoutPIDLockFile, self).acquire(timeout, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/daemon/pidlockfile.py", line 59, in acquire
    super(PIDLockFile, self).acquire(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/lockfile.py", line 239, in acquire
    raise LockFailed("failed to create %%s" %% self.unique_name)
LockFailed: failed to create /var/run/cam1.MainThread-1015

**Comment by jricardogil** [comment]
[UPDATE]
Hello
I have connected from the client to a server successfully, captured images and downloaded them, but it only find one server at the same time, I mean It can only find one server of any pi I connect, but if i have more than one pi connected it only find 1 anyway, what can I do I have set network 169.254.0.0/16
And pi1 ip address = 169.254.93.67/16
      pi2 ip address = 169.254.6.30/16

**Comment by waveform80** [comment]
I don't know if broadcasts work with link-local addressing, as you're using here. Try switching to a private range like 192.168.0.0/16 or 10.0.0.0/8 and see if that fixes things.

**Comment by jricardogil** [comment]
It works if i chanage to a ip static or how can I change to a  range 192.168.0.0/16.  I have the 2 pi Zero connected to a pi 3 with OTG(USB) so the pi3 detect the pi Zero as an ethernet device.
Thanks for the reply.

**Comment by jricardogil** [comment]
[UPDATE]
I have detected the issue now, I cant ping the cameras if I have connected them in the same subnet, I need to set the network to a diferent subnet to find the server, is there  a way to control the cameras with 2 different subnet?
For example:

cam1=192.168.11.2/24
cam2=192.168.12.2/24
That is the only way I can ping the pi zeros and get response back.
